### ISSUE TITLE
Throw a flag where author is dead

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#88]
Basically say: see a lawyer when it comes time to file; who has the right is complicated.

**Comment by briannaschofield** [comment]
Since the tool does not collect information on whether any of the authors are no longer alive (it only asks if at least one is alive, so there is nothing to trigger this flag), and because the FAQ cover the complications that follow if an author is no longer living, we decided to leave the output form as is.

**Comment by briannaschofield** [comment]
(I consider this issue closed, but I don't seem to have the authority to close it.)
